instrumentation:
    root: source
    excludes:
      - "generated-tests/**"
    include-all-sources: true
reporting:
    print: summary
    reports:
        - json-summary
        - html
    dir: ./.coverage
    report-config:
        json-summary: {file: json-summary/coverage-summary.json}
