const browserMap = require('../../src/browser-map');

it('should construct marko 4 browser-map', () => {
  expect(browserMap).toEqual({
    'marko/dist/core-tags/components/component-globals-tag.js': 'marko/dist/core-tags/components/component-globals-tag-browser.js',
    'marko/dist/core-tags/components/getRequirePath.js': 'marko/dist/core-tags/components/getRequirePath-browser.js',
    'marko/dist/core-tags/components/init-components-tag.js': 'marko/dist/core-tags/components/init-components-tag-browser.js',
    'marko/dist/core-tags/components/preserve-tag.js': 'marko/dist/core-tags/components/preserve-tag-browser.js',
    'marko/dist/core-tags/core/await/client-reorder.js': 'marko/dist/core-tags/core/await/client-reorder-browser.js',
    'marko/dist/core-tags/core/await/reorderer-renderer.js': 'marko/dist/core-tags/core/await/noop-render.js',
    'marko/dist/core-tags/core/include-html-tag.js': 'marko/dist/core-tags/core/include-html-tag-browser.js',
    'marko/dist/core-tags/core/include-text-tag.js': 'marko/dist/core-tags/core/include-text-tag-browser.js',
    'marko/dist/index.js': 'marko/dist/index-browser.js',
    'marko/dist/loader/index.js': 'marko/dist/loader/index-browser.js',
    'marko/dist/runtime/components/beginComponent.js': 'marko/dist/runtime/components/beginComponent-browser.js',
    'marko/dist/runtime/components/endComponent.js': 'marko/dist/runtime/components/endComponent-browser.js',
    'marko/dist/runtime/components/helpers.js': 'marko/dist/runtime/components/helpers-browser.js',
    'marko/dist/runtime/components/index.js': 'marko/dist/runtime/components/index-browser.js',
    'marko/dist/runtime/components/init-components.js': 'marko/dist/runtime/components/init-components-browser.js',
    'marko/dist/runtime/components/legacy/defineWidget-legacy.js': 'marko/dist/runtime/components/legacy/defineWidget-legacy-browser.js',
    'marko/dist/runtime/components/legacy/helpers.js': 'marko/dist/runtime/components/legacy/helpers-browser.js',
    'marko/dist/runtime/components/legacy/index.js': 'marko/dist/runtime/components/legacy/index-browser.js',
    'marko/dist/runtime/components/registry.js': 'marko/dist/runtime/components/registry-browser.js',
    'marko/dist/runtime/components/util.js': 'marko/dist/runtime/components/util-browser.js',
    'marko/src/core-tags/components/component-globals-tag.js': 'marko/src/core-tags/components/component-globals-tag-browser.js',
    'marko/src/core-tags/components/getRequirePath.js': 'marko/src/core-tags/components/getRequirePath-browser.js',
    'marko/src/core-tags/components/init-components-tag.js': 'marko/src/core-tags/components/init-components-tag-browser.js',
    'marko/src/core-tags/components/preserve-tag.js': 'marko/src/core-tags/components/preserve-tag-browser.js',
    'marko/src/core-tags/core/await/client-reorder.js': 'marko/src/core-tags/core/await/client-reorder-browser.js',
    'marko/src/core-tags/core/await/reorderer-renderer.js': 'marko/src/core-tags/core/await/noop-render.js',
    'marko/src/core-tags/core/include-html-tag.js': 'marko/src/core-tags/core/include-html-tag-browser.js',
    'marko/src/core-tags/core/include-text-tag.js': 'marko/src/core-tags/core/include-text-tag-browser.js',
    'marko/src/index.js': 'marko/src/index-browser.js',
    'marko/src/loader/index.js': 'marko/src/loader/index-browser.js',
    'marko/src/runtime/components/beginComponent.js': 'marko/src/runtime/components/beginComponent-browser.js',
    'marko/src/runtime/components/endComponent.js': 'marko/src/runtime/components/endComponent-browser.js',
    'marko/src/runtime/components/helpers.js': 'marko/src/runtime/components/helpers-browser.js',
    'marko/src/runtime/components/index.js': 'marko/src/runtime/components/index-browser.js',
    'marko/src/runtime/components/init-components.js': 'marko/src/runtime/components/init-components-browser.js',
    'marko/src/runtime/components/legacy/defineWidget-legacy.js': 'marko/src/runtime/components/legacy/defineWidget-legacy-browser.js',
    'marko/src/runtime/components/legacy/helpers.js': 'marko/src/runtime/components/legacy/helpers-browser.js',
    'marko/src/runtime/components/legacy/index.js': 'marko/src/runtime/components/legacy/index-browser.js',
    'marko/src/runtime/components/registry.js': 'marko/src/runtime/components/registry-browser.js',
    'marko/src/runtime/components/util.js': 'marko/src/runtime/components/util-browser.js',
  });
});
